---
- name: Restart Journald service
  become: true
  service:
    name: "{{ _service_name }}"
    state: restarted
  listen: Restart service
  ignore_errors: true

- name: Remove managed journald.conf files
  become: true
  when: journald_configs is defined and journald_configs|length > 0
  find:
    paths: "{{ item.path|default(_default_config_path) }}"
    patterns: "{{ item.name|default(_default_config_file) }}*"
  with_items: "{{ journald_configs }}"
  register: found_configs

- name: Delete all matched journald.conf files
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ found_configs.results | map(attribute='files') | flatten }}"
  listen: Uninstall config
